### ISSUE TITLE
POST /users has query parameters

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/user-management#2]
If I understand the documentation correctly, it seems like the POST /users call supports URL query parameters.

As far as I'm aware this is legal in HTTP, but it is a bit odd and would be unfamiliar to most web developers. Is there a specific reason the POST needs query paramter support?

**Comment by toraonaca** [comment]
I originally designed a /register_user resource and then replaced it with POST on /users.

The problem is this: the registration process itself is not just the creation of the user, but also the sending out of the email (that contains dynamic links - which is why I need all those different query params), densing out the email with delay, attaching a tenant (partner). 

I read at some point that you can hide all the ugliness in the query params. 

Any suggestions on this?

**Comment by mitraman** [comment]
It's important to get a sense of what would be easier for the user of your API.  Putting theses parameters in the query, might make it look cleaner in documentation, but does that make it easier to understand and code?  Try to get someone to write a simple client if you want to know for sure.

Personally, I wouldn't have a problem with something like this:
```javascript
 POST /users
 {
  confirmationEmail: {
    partner_id: 223,
    pr_success: 'http://server.com/success'  
  },
  user: {
    name: 'Tora',
    phone: '0828832023'
  }
 }
```
This way I can easily create a JSON object to describe what I want the system to do, rather than dealing with a query parameter name-value map.  But, that's just me.

**Comment by toraonaca** [comment]
Ok, then I can include the registration workflow information in the request object.
